// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $imprint from "./routes/imprint.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $Project from "./islands/Project.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/imprint.tsx": $imprint,
    "./routes/index.tsx": $index,
    "./routes/privacy.tsx": $privacy,
  },
  islands: {
    "./islands/Project.tsx": $Project,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
